export type CCAA =
  | 'Andalucía'
  | 'Aragón'
  | 'Asturias'
  | 'Baleares'
  | 'Canarias'
  | 'Cantabria'
  | 'Castilla y Leon'
  | 'Castilla La Mancha'
  | 'Cataluña'
  | 'C. Valenciana'
  | 'Extremadura'
  | 'Galicia'
  | 'La Rioja'
  | 'Madrid'
  | 'Murcia'
  | 'Navarra'
  | 'País Vasco'
  | 'Ceuta'
  | 'Melilla'
  | 'Totales'